//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Manager
{
    private TransactionDB transDB = new TransactionDB();
    private List<string[]> rebateTs = new List<string[]>();
    private List<float> rebateVs = new List<float>();
    private string[] tNums;

    public TransactionDB TransactionDB
    {
        get
        {
            throw new System.NotImplementedException();
        }

        set
        {
        }
    }

    public void returnItem(int id, string name)
	{
        name = name.ToUpper();
        if(transDB.getTransaction(id).getItem(name) != null)
        {
            Item i = transDB.getTransaction(id).getItem(name);
            i.Returned = true;
            i.Amount--;
            i.RAmount++;
        }
        else
        {
            Console.WriteLine("Not a item on the reciept");
        }
        
	}
	public void addTransaction(int id)
	{
        transDB.addTransaction(id);
	}

	public void addItem(int id, string name, float price, int amount)
	{
        name = name.ToUpper();
        transDB.getTransaction(id).addItem(name, price, amount);
	}

    public string genReceipt(int id)
    {
        return transDB.getTransaction(id).genReciept();
    }

    public string checkRebate(string s, string[] reb, float intr)
    {
        
        string s1 = s.Substring(0, 2);
        string s2 = s.Substring(2);
        int month = Int32.Parse(s1);
        int day = Int32.Parse(s2);
        string r = "";
        
        if((month > 6 && day > 15) || month > 7)
        {  
            r = "Date has been entered to late to recieve a rebate check";
        }
        else
        {
            rebateTs.Add(reb);
            rebateVs.Add(intr);
            r = "Valid rebate";
        }
        return r;
    }
	public string generateRebate()
	{
        string s = "";
		for(int i = 0; i < rebateTs.Count; i++)
        {
            s+= "\n*********************** Rebate Check ***********************\n" +
                   "Date: 7/1\n" + "Amount: $" + transDB.getTotal(rebateTs[i]) * rebateVs[i] + "\n" +
                   "************************************************************\n";
        }
        return s;         
	}

}

