//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TransactionDB
{
    private Dictionary<int, Transaction> transactions = new Dictionary<int, Transaction>();

    public Dictionary<int, Transaction> Transactions
    {
        get
        {
            return transactions;
        }
    }

    public void addTransaction(int id)
	{
        transactions.Add(id, new Transaction(id));
	}

	public Transaction getTransaction(int id)
	{
        if (transactions.ContainsKey(id))
        {
            return transactions[id];
        }
        return null;
	}

    public float getTotal(string[] s)
    {
        float to = 0;
        for(int i = 0; i < s.Length; i++)
        {
            to += transactions[Int32.Parse(s[i])].Total;

        }
        return to;
    }

}

