//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UI
{
    private Manager manager = new Manager();
    private int transNum = 0;

    public Manager Manager
    {
        get
        {
            throw new System.NotImplementedException();
        }

        set
        {
        }
    }

    public void run()
	{
        string yn = "y";
        while (yn == "y")
        {
            try
            {
                mainScreen();
            }
            catch(Exception x)
            {
                Console.WriteLine("Invalid Input");
            }
            
        }
        

        Console.ReadLine();
	}

	private void mainScreen()
	{
        Console.WriteLine("(1) Create a Sales Transaction");
        Console.WriteLine("(2) Return Item(s)");
        Console.WriteLine("(3) Enter Rebate");
        Console.WriteLine("(4) Generate Rebate Check\n");
        Console.Write("Enter in a valid input: ");
        string input = Console.ReadLine();
        if(input == "1")
        {
            transactionScreen();
        }
        else if(input == "2")
        {
            returnScreen();
        }
        else if(input == "3")
        {
            enterRebateScreen();
        }
        else if(input == "4")
        {
            genRebateScreen();
        }
        else
        {
            Console.WriteLine("Invalid input try again");
        }

    }

	private void transactionScreen()
	{
        string countinue = "y";
        manager.addTransaction(transNum);
		while(countinue == "y")
        {
            Console.Write("Enter Item Name: ");
            string name = Console.ReadLine();
            Console.Write("Enter in the price: ");
            float price = float.Parse(Console.ReadLine());
            Console.Write("Enter in the Qty: ");
            int amount = Int32.Parse(Console.ReadLine());
            Console.Write("Enter in another item (y)es (n)o");
            countinue = Console.ReadLine();
            manager.addItem(transNum, name, price, amount);
        }
        Console.WriteLine(manager.genReceipt(transNum));
        transNum++;
	}

    private void returnScreen()
    {
        string countinue = "y";
        Console.Write("Enter the id of the transaction: ");
        int id = Int32.Parse(Console.ReadLine());
        while (id >= transNum)
        {
            Console.Write("Not a valid transaction try again: ");
            id = Int32.Parse(Console.ReadLine());
        }
        while (countinue == "y")
        {
            Console.Write("Enter Item Name: ");
            string name = Console.ReadLine();
            manager.returnItem(id, name);
            Console.Write("Enter in another item (y)es (n)o");
            countinue = Console.ReadLine();
        }
        Console.WriteLine(manager.genReceipt(id));
    }

	private void enterRebateScreen()
	{
        Console.Write("Enter the rebate percentage: ");
        float r = float.Parse(Console.ReadLine());
        float intr = r / 100;
        Console.Write("Enter the date of the rebate (Example: 01-09): ");
        string s = Console.ReadLine();
        Console.Write("Enter in transaction numbers (1,2,3,..): ");
        string str = Console.ReadLine();
        string[] nums = str.Split(',');
        if (str.Length < 2)
        {
            nums = new string[1];
            nums[0] = str;
        }
        foreach (string st in nums)
        {
            if (Int32.Parse(st) >= transNum)
            {
                Console.WriteLine("invalid transaction number");
                break;
            }
        }
        Console.WriteLine(manager.checkRebate(s,nums,intr));
    }

	private void genRebateScreen()
	{
        Console.WriteLine(manager.generateRebate());
	}

}

